# Generated by Django 5.2.12 on 2026-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the image.', max_length=255)),
                ('image', models.ImageField(help_text='The image file to upload.', upload_to='shared/images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the image was uploaded.')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-upload_date'],
            },
        ),
    ]
