# Generated by Django 5.2.12 on 2026-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True, null=True)),
                ('preview', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('deployed', 'Deployed'), ('in_development', 'In Development')], default='in_development', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Markdown content')),
                ('date', models.CharField(max_length=255)),
                ('is_cv_highlight', models.BooleanField(default=False)),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.technology')),
            ],
        ),
    ]
