# Generated by Django 5.2.12 on 2026-03-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='slug',
        ),
    ]
