# Generated by Django 5.2.12 on 2026-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(help_text='Main body content of the project page (Markdown format).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(help_text='Year or date range of the project (e.g., 2023).', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='A short summary of the project for cards.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, help_text='A detailed overview for the sidebar.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.SlugField(help_text='Unique identifier for the project URL (slug).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the project.', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_cv_highlight',
            field=models.BooleanField(default=False, help_text='If checked, this project will be highlighted in the CV section.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text="URL to the project's source code (e.g., GitHub, Gitea).", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.URLField(blank=True, help_text='URL to a live demo or production site.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('deployed', 'Deployed'), ('in_development', 'In Development')], default='in_development', help_text='Current status of the project (e.g., Deployed, In Development).', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='List of technologies used in this project.', related_name='projects', to='portfolio.technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='The name of the project.', max_length=255),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(help_text='The name of the technology (e.g., Python, React).', max_length=255, unique=True),
        ),
    ]
