# Generated by Django 5.2.12 on 2026-04-01 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_content_alter_project_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="A specific task or achievement in this project (e.g., 'Coded in Arduino').", max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Task',
                'ordering': ['order'],
            },
        ),
    ]
