# Generated by Django 5.2.12 on 2026-03-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aeronautical_skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.CreateModel(
            name='AeronauticalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeronautical_skills', to='cv.profile')),
            ],
            options={
                'verbose_name': 'Aeronautical Skill',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='cv.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
