# Generated by Django 5.2.12 on 2026-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_profile_aeronautical_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronauticalskill',
            name='name',
            field=models.CharField(help_text='Aeronautical skill, certification, or experience (e.g., LAPL Student Pilot).', max_length=255),
        ),
        migrations.AlterField(
            model_name='aeronauticalskill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_range',
            field=models.CharField(help_text='The time period of the education (e.g., 02/2024 – 06/2026).', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='details',
            field=models.TextField(help_text='Specific details, degrees, or specializations (supports multiple lines).'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='The name of the school or university.', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(help_text='The name of the company or organization.', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_range',
            field=models.CharField(help_text='The time period of the experience (e.g., 10/2025 – 08/2026).', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(help_text='Your role or job title during this period.', max_length=255),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(help_text='A personal interest or hobby (e.g., Aviation, Video Editing).', max_length=255),
        ),
        migrations.AlterField(
            model_name='interest',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(help_text='Proficiency level (e.g., Native, TOEIC 940).', max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='The name of the language (e.g., English).', max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(help_text="A short professional biography or 'About Me' section."),
        ),
        migrations.AlterField(
            model_name='profile',
            name='driving_license',
            field=models.CharField(help_text='Driving license status or category (e.g., Category B - Vehicle Owner).', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(help_text='Professional email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(help_text='Link to your professional LinkedIn profile.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Full name of the profile (e.g., LÉONARD-ANTON LLOSA).', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Contact phone number (e.g., +33 6 62 38 65 96).', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(help_text='Professional title or current position (e.g., Future Network & Security Engineer).', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='details',
            field=models.CharField(blank=True, help_text='Additional details or tools for this skill (e.g., Ansible, n8n).', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='The specific skill name (e.g., Automation).', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(help_text='The name of the skill category (e.g., SYSTEMS & DEVSECOPS).', max_length=255),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).'),
        ),
    ]
