# Generated by Django 5.2.12 on 2026-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_aeronauticalskill_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronauticalskill',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='language',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower numbers appear first).'),
        ),
    ]
